[package]
name = "platform"
version = "0.1.0"
edition = "2024"
description = "Alat platform-specific bindings"
authors.workspace = true
documentation.workspace = true


[dependencies]
nlem = { path = "../nlem" }
